// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GenerateRS.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace AppleRemoteAuth {

  /// <summary>Holder for reflection information generated from GenerateRS.proto</summary>
  public static partial class GenerateRSReflection {

    #region Descriptor
    /// <summary>File descriptor for GenerateRS.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GenerateRSReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBHZW5lcmF0ZVJTLnByb3RvEg9BcHBsZVJlbW90ZUF1dGgi4AEKEFJlbW90",
            "ZURldmljZUluZm8SDwoHcnFfZGF0YRgBIAEoDBITCgtycV9zaWdfZGF0YRgC",
            "IAEoDBIZChFncmFwcGFfc2Vzc2lvbl9pZBgDIAEoDRIdChVmYWlyX3BsYXlf",
            "Y2VydGlmaWNhdGUYBSABKAwSGAoQZmFpcl9kZXZpY2VfdHlwZRgGIAEoAxIW",
            "Cg5mYWlyX3BsYXlfZ3VpZBgIIAEoCRITCgZncmFwcGEYCSABKAxIAIgBARIR",
            "CgRkc2lkGAogASgDSAGIAQFCCQoHX2dyYXBwYUIHCgVfZHNpZCJQCgZyc2Rh",
            "dGESDwoHcnNfZGF0YRgBIAEoDBILCgNyZXQYAiABKAgSGAoLcnNfc2lnX2Rh",
            "dGEYAyABKAxIAIgBAUIOCgxfcnNfc2lnX2RhdGEiRAoGR3JhcHBhEhIKCmdy",
            "YXBwYURhdGEYASABKAwSGQoRZ3JhcHBhX3Nlc3Npb25faWQYAiABKA0SCwoD",
            "cmV0GAMgASgIIhwKDHJxR2VuZUdyYXBwYRIMCgR1ZGlkGAEgASgJImYKBnNj",
            "aW5mbxIPCgdhcHBsZWlkGAEgASgJEgwKBGRzaWQYAiABKAMSDAoEc2lkYhgD",
            "IAEoDBIMCgRzaWRkGAQgASgMEgsKA3R4dBgFIAEoDBIUCgxoYXJkd2FyZUlu",
            "Zm8YBiABKAwiFwoIcnNzY2luZm8SCwoDcmV0GAEgASgIMuMBCgNhaWQSSgoK",
            "R2VuZXJhdGVSUxIhLkFwcGxlUmVtb3RlQXV0aC5SZW1vdGVEZXZpY2VJbmZv",
            "GhcuQXBwbGVSZW1vdGVBdXRoLnJzZGF0YSIAEkoKDkdlbmVyYXRlR3JhcHBh",
            "Eh0uQXBwbGVSZW1vdGVBdXRoLnJxR2VuZUdyYXBwYRoXLkFwcGxlUmVtb3Rl",
            "QXV0aC5HcmFwcGEiABJECgxVcGxvYWRTY2luZm8SFy5BcHBsZVJlbW90ZUF1",
            "dGguc2NpbmZvGhkuQXBwbGVSZW1vdGVBdXRoLnJzc2NpbmZvIgBiBnByb3Rv",
            "Mw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::AppleRemoteAuth.RemoteDeviceInfo), global::AppleRemoteAuth.RemoteDeviceInfo.Parser, new[]{ "RqData", "RqSigData", "GrappaSessionId", "FairPlayCertificate", "FairDeviceType", "FairPlayGuid", "Grappa", "Dsid" }, new[]{ "Grappa", "Dsid" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AppleRemoteAuth.rsdata), global::AppleRemoteAuth.rsdata.Parser, new[]{ "RsData", "Ret", "RsSigData" }, new[]{ "RsSigData" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AppleRemoteAuth.Grappa), global::AppleRemoteAuth.Grappa.Parser, new[]{ "GrappaData", "GrappaSessionId", "Ret" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AppleRemoteAuth.rqGeneGrappa), global::AppleRemoteAuth.rqGeneGrappa.Parser, new[]{ "Udid" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AppleRemoteAuth.scinfo), global::AppleRemoteAuth.scinfo.Parser, new[]{ "Appleid", "Dsid", "Sidb", "Sidd", "Txt", "HardwareInfo" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AppleRemoteAuth.rsscinfo), global::AppleRemoteAuth.rsscinfo.Parser, new[]{ "Ret" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// The request GenerateRS message 
  /// </summary>
  public sealed partial class RemoteDeviceInfo : pb::IMessage<RemoteDeviceInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RemoteDeviceInfo> _parser = new pb::MessageParser<RemoteDeviceInfo>(() => new RemoteDeviceInfo());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RemoteDeviceInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AppleRemoteAuth.GenerateRSReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RemoteDeviceInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RemoteDeviceInfo(RemoteDeviceInfo other) : this() {
      _hasBits0 = other._hasBits0;
      rqData_ = other.rqData_;
      rqSigData_ = other.rqSigData_;
      grappaSessionId_ = other.grappaSessionId_;
      fairPlayCertificate_ = other.fairPlayCertificate_;
      fairDeviceType_ = other.fairDeviceType_;
      fairPlayGuid_ = other.fairPlayGuid_;
      grappa_ = other.grappa_;
      dsid_ = other.dsid_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RemoteDeviceInfo Clone() {
      return new RemoteDeviceInfo(this);
    }

    /// <summary>Field number for the "rq_data" field.</summary>
    public const int RqDataFieldNumber = 1;
    private pb::ByteString rqData_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString RqData {
      get { return rqData_; }
      set {
        rqData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "rq_sig_data" field.</summary>
    public const int RqSigDataFieldNumber = 2;
    private pb::ByteString rqSigData_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString RqSigData {
      get { return rqSigData_; }
      set {
        rqSigData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "grappa_session_id" field.</summary>
    public const int GrappaSessionIdFieldNumber = 3;
    private uint grappaSessionId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint GrappaSessionId {
      get { return grappaSessionId_; }
      set {
        grappaSessionId_ = value;
      }
    }

    /// <summary>Field number for the "fair_play_certificate" field.</summary>
    public const int FairPlayCertificateFieldNumber = 5;
    private pb::ByteString fairPlayCertificate_ = pb::ByteString.Empty;
    /// <summary>
    ///bytes key_fair_play_guid=4;
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString FairPlayCertificate {
      get { return fairPlayCertificate_; }
      set {
        fairPlayCertificate_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "fair_device_type" field.</summary>
    public const int FairDeviceTypeFieldNumber = 6;
    private long fairDeviceType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long FairDeviceType {
      get { return fairDeviceType_; }
      set {
        fairDeviceType_ = value;
      }
    }

    /// <summary>Field number for the "fair_play_guid" field.</summary>
    public const int FairPlayGuidFieldNumber = 8;
    private string fairPlayGuid_ = "";
    /// <summary>
    ///uint32 private_key=7;
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FairPlayGuid {
      get { return fairPlayGuid_; }
      set {
        fairPlayGuid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "grappa" field.</summary>
    public const int GrappaFieldNumber = 9;
    private pb::ByteString grappa_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Grappa {
      get { return grappa_ ?? pb::ByteString.Empty; }
      set {
        grappa_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "grappa" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasGrappa {
      get { return grappa_ != null; }
    }
    /// <summary>Clears the value of the "grappa" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearGrappa() {
      grappa_ = null;
    }

    /// <summary>Field number for the "dsid" field.</summary>
    public const int DsidFieldNumber = 10;
    private long dsid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Dsid {
      get { if ((_hasBits0 & 1) != 0) { return dsid_; } else { return 0L; } }
      set {
        _hasBits0 |= 1;
        dsid_ = value;
      }
    }
    /// <summary>Gets whether the "dsid" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasDsid {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "dsid" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearDsid() {
      _hasBits0 &= ~1;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RemoteDeviceInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RemoteDeviceInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RqData != other.RqData) return false;
      if (RqSigData != other.RqSigData) return false;
      if (GrappaSessionId != other.GrappaSessionId) return false;
      if (FairPlayCertificate != other.FairPlayCertificate) return false;
      if (FairDeviceType != other.FairDeviceType) return false;
      if (FairPlayGuid != other.FairPlayGuid) return false;
      if (Grappa != other.Grappa) return false;
      if (Dsid != other.Dsid) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (RqData.Length != 0) hash ^= RqData.GetHashCode();
      if (RqSigData.Length != 0) hash ^= RqSigData.GetHashCode();
      if (GrappaSessionId != 0) hash ^= GrappaSessionId.GetHashCode();
      if (FairPlayCertificate.Length != 0) hash ^= FairPlayCertificate.GetHashCode();
      if (FairDeviceType != 0L) hash ^= FairDeviceType.GetHashCode();
      if (FairPlayGuid.Length != 0) hash ^= FairPlayGuid.GetHashCode();
      if (HasGrappa) hash ^= Grappa.GetHashCode();
      if (HasDsid) hash ^= Dsid.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (RqData.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(RqData);
      }
      if (RqSigData.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(RqSigData);
      }
      if (GrappaSessionId != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(GrappaSessionId);
      }
      if (FairPlayCertificate.Length != 0) {
        output.WriteRawTag(42);
        output.WriteBytes(FairPlayCertificate);
      }
      if (FairDeviceType != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(FairDeviceType);
      }
      if (FairPlayGuid.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(FairPlayGuid);
      }
      if (HasGrappa) {
        output.WriteRawTag(74);
        output.WriteBytes(Grappa);
      }
      if (HasDsid) {
        output.WriteRawTag(80);
        output.WriteInt64(Dsid);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (RqData.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(RqData);
      }
      if (RqSigData.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(RqSigData);
      }
      if (GrappaSessionId != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(GrappaSessionId);
      }
      if (FairPlayCertificate.Length != 0) {
        output.WriteRawTag(42);
        output.WriteBytes(FairPlayCertificate);
      }
      if (FairDeviceType != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(FairDeviceType);
      }
      if (FairPlayGuid.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(FairPlayGuid);
      }
      if (HasGrappa) {
        output.WriteRawTag(74);
        output.WriteBytes(Grappa);
      }
      if (HasDsid) {
        output.WriteRawTag(80);
        output.WriteInt64(Dsid);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (RqData.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(RqData);
      }
      if (RqSigData.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(RqSigData);
      }
      if (GrappaSessionId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(GrappaSessionId);
      }
      if (FairPlayCertificate.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(FairPlayCertificate);
      }
      if (FairDeviceType != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(FairDeviceType);
      }
      if (FairPlayGuid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FairPlayGuid);
      }
      if (HasGrappa) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Grappa);
      }
      if (HasDsid) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Dsid);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RemoteDeviceInfo other) {
      if (other == null) {
        return;
      }
      if (other.RqData.Length != 0) {
        RqData = other.RqData;
      }
      if (other.RqSigData.Length != 0) {
        RqSigData = other.RqSigData;
      }
      if (other.GrappaSessionId != 0) {
        GrappaSessionId = other.GrappaSessionId;
      }
      if (other.FairPlayCertificate.Length != 0) {
        FairPlayCertificate = other.FairPlayCertificate;
      }
      if (other.FairDeviceType != 0L) {
        FairDeviceType = other.FairDeviceType;
      }
      if (other.FairPlayGuid.Length != 0) {
        FairPlayGuid = other.FairPlayGuid;
      }
      if (other.HasGrappa) {
        Grappa = other.Grappa;
      }
      if (other.HasDsid) {
        Dsid = other.Dsid;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            RqData = input.ReadBytes();
            break;
          }
          case 18: {
            RqSigData = input.ReadBytes();
            break;
          }
          case 24: {
            GrappaSessionId = input.ReadUInt32();
            break;
          }
          case 42: {
            FairPlayCertificate = input.ReadBytes();
            break;
          }
          case 48: {
            FairDeviceType = input.ReadInt64();
            break;
          }
          case 66: {
            FairPlayGuid = input.ReadString();
            break;
          }
          case 74: {
            Grappa = input.ReadBytes();
            break;
          }
          case 80: {
            Dsid = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            RqData = input.ReadBytes();
            break;
          }
          case 18: {
            RqSigData = input.ReadBytes();
            break;
          }
          case 24: {
            GrappaSessionId = input.ReadUInt32();
            break;
          }
          case 42: {
            FairPlayCertificate = input.ReadBytes();
            break;
          }
          case 48: {
            FairDeviceType = input.ReadInt64();
            break;
          }
          case 66: {
            FairPlayGuid = input.ReadString();
            break;
          }
          case 74: {
            Grappa = input.ReadBytes();
            break;
          }
          case 80: {
            Dsid = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// The response GenerateRS message 
  /// </summary>
  public sealed partial class rsdata : pb::IMessage<rsdata>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<rsdata> _parser = new pb::MessageParser<rsdata>(() => new rsdata());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<rsdata> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AppleRemoteAuth.GenerateRSReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public rsdata() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public rsdata(rsdata other) : this() {
      rsData_ = other.rsData_;
      ret_ = other.ret_;
      rsSigData_ = other.rsSigData_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public rsdata Clone() {
      return new rsdata(this);
    }

    /// <summary>Field number for the "rs_data" field.</summary>
    public const int RsDataFieldNumber = 1;
    private pb::ByteString rsData_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString RsData {
      get { return rsData_; }
      set {
        rsData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ret" field.</summary>
    public const int RetFieldNumber = 2;
    private bool ret_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Ret {
      get { return ret_; }
      set {
        ret_ = value;
      }
    }

    /// <summary>Field number for the "rs_sig_data" field.</summary>
    public const int RsSigDataFieldNumber = 3;
    private pb::ByteString rsSigData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString RsSigData {
      get { return rsSigData_ ?? pb::ByteString.Empty; }
      set {
        rsSigData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "rs_sig_data" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasRsSigData {
      get { return rsSigData_ != null; }
    }
    /// <summary>Clears the value of the "rs_sig_data" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearRsSigData() {
      rsSigData_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as rsdata);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(rsdata other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RsData != other.RsData) return false;
      if (Ret != other.Ret) return false;
      if (RsSigData != other.RsSigData) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (RsData.Length != 0) hash ^= RsData.GetHashCode();
      if (Ret != false) hash ^= Ret.GetHashCode();
      if (HasRsSigData) hash ^= RsSigData.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (RsData.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(RsData);
      }
      if (Ret != false) {
        output.WriteRawTag(16);
        output.WriteBool(Ret);
      }
      if (HasRsSigData) {
        output.WriteRawTag(26);
        output.WriteBytes(RsSigData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (RsData.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(RsData);
      }
      if (Ret != false) {
        output.WriteRawTag(16);
        output.WriteBool(Ret);
      }
      if (HasRsSigData) {
        output.WriteRawTag(26);
        output.WriteBytes(RsSigData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (RsData.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(RsData);
      }
      if (Ret != false) {
        size += 1 + 1;
      }
      if (HasRsSigData) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(RsSigData);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(rsdata other) {
      if (other == null) {
        return;
      }
      if (other.RsData.Length != 0) {
        RsData = other.RsData;
      }
      if (other.Ret != false) {
        Ret = other.Ret;
      }
      if (other.HasRsSigData) {
        RsSigData = other.RsSigData;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            RsData = input.ReadBytes();
            break;
          }
          case 16: {
            Ret = input.ReadBool();
            break;
          }
          case 26: {
            RsSigData = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            RsData = input.ReadBytes();
            break;
          }
          case 16: {
            Ret = input.ReadBool();
            break;
          }
          case 26: {
            RsSigData = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// The response GenerateGrappa message 
  /// </summary>
  public sealed partial class Grappa : pb::IMessage<Grappa>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Grappa> _parser = new pb::MessageParser<Grappa>(() => new Grappa());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Grappa> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AppleRemoteAuth.GenerateRSReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Grappa() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Grappa(Grappa other) : this() {
      grappaData_ = other.grappaData_;
      grappaSessionId_ = other.grappaSessionId_;
      ret_ = other.ret_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Grappa Clone() {
      return new Grappa(this);
    }

    /// <summary>Field number for the "grappaData" field.</summary>
    public const int GrappaDataFieldNumber = 1;
    private pb::ByteString grappaData_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString GrappaData {
      get { return grappaData_; }
      set {
        grappaData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "grappa_session_id" field.</summary>
    public const int GrappaSessionIdFieldNumber = 2;
    private uint grappaSessionId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint GrappaSessionId {
      get { return grappaSessionId_; }
      set {
        grappaSessionId_ = value;
      }
    }

    /// <summary>Field number for the "ret" field.</summary>
    public const int RetFieldNumber = 3;
    private bool ret_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Ret {
      get { return ret_; }
      set {
        ret_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Grappa);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Grappa other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (GrappaData != other.GrappaData) return false;
      if (GrappaSessionId != other.GrappaSessionId) return false;
      if (Ret != other.Ret) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (GrappaData.Length != 0) hash ^= GrappaData.GetHashCode();
      if (GrappaSessionId != 0) hash ^= GrappaSessionId.GetHashCode();
      if (Ret != false) hash ^= Ret.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (GrappaData.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(GrappaData);
      }
      if (GrappaSessionId != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(GrappaSessionId);
      }
      if (Ret != false) {
        output.WriteRawTag(24);
        output.WriteBool(Ret);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (GrappaData.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(GrappaData);
      }
      if (GrappaSessionId != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(GrappaSessionId);
      }
      if (Ret != false) {
        output.WriteRawTag(24);
        output.WriteBool(Ret);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (GrappaData.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(GrappaData);
      }
      if (GrappaSessionId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(GrappaSessionId);
      }
      if (Ret != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Grappa other) {
      if (other == null) {
        return;
      }
      if (other.GrappaData.Length != 0) {
        GrappaData = other.GrappaData;
      }
      if (other.GrappaSessionId != 0) {
        GrappaSessionId = other.GrappaSessionId;
      }
      if (other.Ret != false) {
        Ret = other.Ret;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            GrappaData = input.ReadBytes();
            break;
          }
          case 16: {
            GrappaSessionId = input.ReadUInt32();
            break;
          }
          case 24: {
            Ret = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            GrappaData = input.ReadBytes();
            break;
          }
          case 16: {
            GrappaSessionId = input.ReadUInt32();
            break;
          }
          case 24: {
            Ret = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// The request GenerateGrappa message 
  /// </summary>
  public sealed partial class rqGeneGrappa : pb::IMessage<rqGeneGrappa>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<rqGeneGrappa> _parser = new pb::MessageParser<rqGeneGrappa>(() => new rqGeneGrappa());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<rqGeneGrappa> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AppleRemoteAuth.GenerateRSReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public rqGeneGrappa() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public rqGeneGrappa(rqGeneGrappa other) : this() {
      udid_ = other.udid_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public rqGeneGrappa Clone() {
      return new rqGeneGrappa(this);
    }

    /// <summary>Field number for the "udid" field.</summary>
    public const int UdidFieldNumber = 1;
    private string udid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Udid {
      get { return udid_; }
      set {
        udid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as rqGeneGrappa);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(rqGeneGrappa other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Udid != other.Udid) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Udid.Length != 0) hash ^= Udid.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Udid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Udid);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Udid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Udid);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Udid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Udid);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(rqGeneGrappa other) {
      if (other == null) {
        return;
      }
      if (other.Udid.Length != 0) {
        Udid = other.Udid;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Udid = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Udid = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// the scinfo
  /// </summary>
  public sealed partial class scinfo : pb::IMessage<scinfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<scinfo> _parser = new pb::MessageParser<scinfo>(() => new scinfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<scinfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AppleRemoteAuth.GenerateRSReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public scinfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public scinfo(scinfo other) : this() {
      appleid_ = other.appleid_;
      dsid_ = other.dsid_;
      sidb_ = other.sidb_;
      sidd_ = other.sidd_;
      txt_ = other.txt_;
      hardwareInfo_ = other.hardwareInfo_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public scinfo Clone() {
      return new scinfo(this);
    }

    /// <summary>Field number for the "appleid" field.</summary>
    public const int AppleidFieldNumber = 1;
    private string appleid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Appleid {
      get { return appleid_; }
      set {
        appleid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "dsid" field.</summary>
    public const int DsidFieldNumber = 2;
    private long dsid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Dsid {
      get { return dsid_; }
      set {
        dsid_ = value;
      }
    }

    /// <summary>Field number for the "sidb" field.</summary>
    public const int SidbFieldNumber = 3;
    private pb::ByteString sidb_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Sidb {
      get { return sidb_; }
      set {
        sidb_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "sidd" field.</summary>
    public const int SiddFieldNumber = 4;
    private pb::ByteString sidd_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Sidd {
      get { return sidd_; }
      set {
        sidd_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "txt" field.</summary>
    public const int TxtFieldNumber = 5;
    private pb::ByteString txt_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Txt {
      get { return txt_; }
      set {
        txt_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "hardwareInfo" field.</summary>
    public const int HardwareInfoFieldNumber = 6;
    private pb::ByteString hardwareInfo_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString HardwareInfo {
      get { return hardwareInfo_; }
      set {
        hardwareInfo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as scinfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(scinfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Appleid != other.Appleid) return false;
      if (Dsid != other.Dsid) return false;
      if (Sidb != other.Sidb) return false;
      if (Sidd != other.Sidd) return false;
      if (Txt != other.Txt) return false;
      if (HardwareInfo != other.HardwareInfo) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Appleid.Length != 0) hash ^= Appleid.GetHashCode();
      if (Dsid != 0L) hash ^= Dsid.GetHashCode();
      if (Sidb.Length != 0) hash ^= Sidb.GetHashCode();
      if (Sidd.Length != 0) hash ^= Sidd.GetHashCode();
      if (Txt.Length != 0) hash ^= Txt.GetHashCode();
      if (HardwareInfo.Length != 0) hash ^= HardwareInfo.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Appleid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Appleid);
      }
      if (Dsid != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Dsid);
      }
      if (Sidb.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(Sidb);
      }
      if (Sidd.Length != 0) {
        output.WriteRawTag(34);
        output.WriteBytes(Sidd);
      }
      if (Txt.Length != 0) {
        output.WriteRawTag(42);
        output.WriteBytes(Txt);
      }
      if (HardwareInfo.Length != 0) {
        output.WriteRawTag(50);
        output.WriteBytes(HardwareInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Appleid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Appleid);
      }
      if (Dsid != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Dsid);
      }
      if (Sidb.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(Sidb);
      }
      if (Sidd.Length != 0) {
        output.WriteRawTag(34);
        output.WriteBytes(Sidd);
      }
      if (Txt.Length != 0) {
        output.WriteRawTag(42);
        output.WriteBytes(Txt);
      }
      if (HardwareInfo.Length != 0) {
        output.WriteRawTag(50);
        output.WriteBytes(HardwareInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Appleid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Appleid);
      }
      if (Dsid != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Dsid);
      }
      if (Sidb.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Sidb);
      }
      if (Sidd.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Sidd);
      }
      if (Txt.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Txt);
      }
      if (HardwareInfo.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(HardwareInfo);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(scinfo other) {
      if (other == null) {
        return;
      }
      if (other.Appleid.Length != 0) {
        Appleid = other.Appleid;
      }
      if (other.Dsid != 0L) {
        Dsid = other.Dsid;
      }
      if (other.Sidb.Length != 0) {
        Sidb = other.Sidb;
      }
      if (other.Sidd.Length != 0) {
        Sidd = other.Sidd;
      }
      if (other.Txt.Length != 0) {
        Txt = other.Txt;
      }
      if (other.HardwareInfo.Length != 0) {
        HardwareInfo = other.HardwareInfo;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Appleid = input.ReadString();
            break;
          }
          case 16: {
            Dsid = input.ReadInt64();
            break;
          }
          case 26: {
            Sidb = input.ReadBytes();
            break;
          }
          case 34: {
            Sidd = input.ReadBytes();
            break;
          }
          case 42: {
            Txt = input.ReadBytes();
            break;
          }
          case 50: {
            HardwareInfo = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Appleid = input.ReadString();
            break;
          }
          case 16: {
            Dsid = input.ReadInt64();
            break;
          }
          case 26: {
            Sidb = input.ReadBytes();
            break;
          }
          case 34: {
            Sidd = input.ReadBytes();
            break;
          }
          case 42: {
            Txt = input.ReadBytes();
            break;
          }
          case 50: {
            HardwareInfo = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// The response  scinfo
  /// </summary>
  public sealed partial class rsscinfo : pb::IMessage<rsscinfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<rsscinfo> _parser = new pb::MessageParser<rsscinfo>(() => new rsscinfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<rsscinfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AppleRemoteAuth.GenerateRSReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public rsscinfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public rsscinfo(rsscinfo other) : this() {
      ret_ = other.ret_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public rsscinfo Clone() {
      return new rsscinfo(this);
    }

    /// <summary>Field number for the "ret" field.</summary>
    public const int RetFieldNumber = 1;
    private bool ret_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Ret {
      get { return ret_; }
      set {
        ret_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as rsscinfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(rsscinfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Ret != other.Ret) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Ret != false) hash ^= Ret.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Ret != false) {
        output.WriteRawTag(8);
        output.WriteBool(Ret);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Ret != false) {
        output.WriteRawTag(8);
        output.WriteBool(Ret);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Ret != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(rsscinfo other) {
      if (other == null) {
        return;
      }
      if (other.Ret != false) {
        Ret = other.Ret;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Ret = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Ret = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
