// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GenerateRS.proto

#include "GenerateRS.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace AppleRemoteAuth {
PROTOBUF_CONSTEXPR RemoteDeviceInfo::RemoteDeviceInfo(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.rq_data_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.rq_sig_data_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.fair_play_certificate_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.fair_play_guid_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.grappa_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.fair_device_type_)*/int64_t{0}
  , /*decltype(_impl_.dsid_)*/int64_t{0}
  , /*decltype(_impl_.grappa_session_id_)*/0u} {}
struct RemoteDeviceInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RemoteDeviceInfoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~RemoteDeviceInfoDefaultTypeInternal() {}
  union {
    RemoteDeviceInfo _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RemoteDeviceInfoDefaultTypeInternal _RemoteDeviceInfo_default_instance_;
PROTOBUF_CONSTEXPR rsdata::rsdata(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.rs_data_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.rs_sig_data_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.ret_)*/false} {}
struct rsdataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR rsdataDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~rsdataDefaultTypeInternal() {}
  union {
    rsdata _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 rsdataDefaultTypeInternal _rsdata_default_instance_;
PROTOBUF_CONSTEXPR Grappa::Grappa(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.grappadata_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.grappa_session_id_)*/0u
  , /*decltype(_impl_.ret_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct GrappaDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GrappaDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GrappaDefaultTypeInternal() {}
  union {
    Grappa _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GrappaDefaultTypeInternal _Grappa_default_instance_;
PROTOBUF_CONSTEXPR rqGeneGrappa::rqGeneGrappa(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.udid_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct rqGeneGrappaDefaultTypeInternal {
  PROTOBUF_CONSTEXPR rqGeneGrappaDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~rqGeneGrappaDefaultTypeInternal() {}
  union {
    rqGeneGrappa _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 rqGeneGrappaDefaultTypeInternal _rqGeneGrappa_default_instance_;
PROTOBUF_CONSTEXPR scinfo::scinfo(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.appleid_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.sidb_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.sidd_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.txt_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.hardwareinfo_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.dsid_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct scinfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR scinfoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~scinfoDefaultTypeInternal() {}
  union {
    scinfo _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 scinfoDefaultTypeInternal _scinfo_default_instance_;
PROTOBUF_CONSTEXPR rsscinfo::rsscinfo(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.ret_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct rsscinfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR rsscinfoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~rsscinfoDefaultTypeInternal() {}
  union {
    rsscinfo _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 rsscinfoDefaultTypeInternal _rsscinfo_default_instance_;
}  // namespace AppleRemoteAuth
static ::_pb::Metadata file_level_metadata_GenerateRS_2eproto[6];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_GenerateRS_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_GenerateRS_2eproto = nullptr;

const uint32_t TableStruct_GenerateRS_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::AppleRemoteAuth::RemoteDeviceInfo, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::AppleRemoteAuth::RemoteDeviceInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::AppleRemoteAuth::RemoteDeviceInfo, _impl_.rq_data_),
  PROTOBUF_FIELD_OFFSET(::AppleRemoteAuth::RemoteDeviceInfo, _impl_.rq_sig_data_),
  PROTOBUF_FIELD_OFFSET(::AppleRemoteAuth::RemoteDeviceInfo, _impl_.grappa_session_id_),
  PROTOBUF_FIELD_OFFSET(::AppleRemoteAuth::RemoteDeviceInfo, _impl_.fair_play_certificate_),
  PROTOBUF_FIELD_OFFSET(::AppleRemoteAuth::RemoteDeviceInfo, _impl_.fair_device_type_),
  PROTOBUF_FIELD_OFFSET(::AppleRemoteAuth::RemoteDeviceInfo, _impl_.fair_play_guid_),
  PROTOBUF_FIELD_OFFSET(::AppleRemoteAuth::RemoteDeviceInfo, _impl_.grappa_),
  PROTOBUF_FIELD_OFFSET(::AppleRemoteAuth::RemoteDeviceInfo, _impl_.dsid_),
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  0,
  1,
  PROTOBUF_FIELD_OFFSET(::AppleRemoteAuth::rsdata, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::AppleRemoteAuth::rsdata, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::AppleRemoteAuth::rsdata, _impl_.rs_data_),
  PROTOBUF_FIELD_OFFSET(::AppleRemoteAuth::rsdata, _impl_.ret_),
  PROTOBUF_FIELD_OFFSET(::AppleRemoteAuth::rsdata, _impl_.rs_sig_data_),
  ~0u,
  ~0u,
  0,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::AppleRemoteAuth::Grappa, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::AppleRemoteAuth::Grappa, _impl_.grappadata_),
  PROTOBUF_FIELD_OFFSET(::AppleRemoteAuth::Grappa, _impl_.grappa_session_id_),
  PROTOBUF_FIELD_OFFSET(::AppleRemoteAuth::Grappa, _impl_.ret_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::AppleRemoteAuth::rqGeneGrappa, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::AppleRemoteAuth::rqGeneGrappa, _impl_.udid_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::AppleRemoteAuth::scinfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::AppleRemoteAuth::scinfo, _impl_.appleid_),
  PROTOBUF_FIELD_OFFSET(::AppleRemoteAuth::scinfo, _impl_.dsid_),
  PROTOBUF_FIELD_OFFSET(::AppleRemoteAuth::scinfo, _impl_.sidb_),
  PROTOBUF_FIELD_OFFSET(::AppleRemoteAuth::scinfo, _impl_.sidd_),
  PROTOBUF_FIELD_OFFSET(::AppleRemoteAuth::scinfo, _impl_.txt_),
  PROTOBUF_FIELD_OFFSET(::AppleRemoteAuth::scinfo, _impl_.hardwareinfo_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::AppleRemoteAuth::rsscinfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::AppleRemoteAuth::rsscinfo, _impl_.ret_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 14, -1, sizeof(::AppleRemoteAuth::RemoteDeviceInfo)},
  { 22, 31, -1, sizeof(::AppleRemoteAuth::rsdata)},
  { 34, -1, -1, sizeof(::AppleRemoteAuth::Grappa)},
  { 43, -1, -1, sizeof(::AppleRemoteAuth::rqGeneGrappa)},
  { 50, -1, -1, sizeof(::AppleRemoteAuth::scinfo)},
  { 62, -1, -1, sizeof(::AppleRemoteAuth::rsscinfo)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::AppleRemoteAuth::_RemoteDeviceInfo_default_instance_._instance,
  &::AppleRemoteAuth::_rsdata_default_instance_._instance,
  &::AppleRemoteAuth::_Grappa_default_instance_._instance,
  &::AppleRemoteAuth::_rqGeneGrappa_default_instance_._instance,
  &::AppleRemoteAuth::_scinfo_default_instance_._instance,
  &::AppleRemoteAuth::_rsscinfo_default_instance_._instance,
};

const char descriptor_table_protodef_GenerateRS_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\020GenerateRS.proto\022\017AppleRemoteAuth\"\340\001\n\020"
  "RemoteDeviceInfo\022\017\n\007rq_data\030\001 \001(\014\022\023\n\013rq_"
  "sig_data\030\002 \001(\014\022\031\n\021grappa_session_id\030\003 \001("
  "\r\022\035\n\025fair_play_certificate\030\005 \001(\014\022\030\n\020fair"
  "_device_type\030\006 \001(\003\022\026\n\016fair_play_guid\030\010 \001"
  "(\t\022\023\n\006grappa\030\t \001(\014H\000\210\001\001\022\021\n\004dsid\030\n \001(\003H\001\210"
  "\001\001B\t\n\007_grappaB\007\n\005_dsid\"P\n\006rsdata\022\017\n\007rs_d"
  "ata\030\001 \001(\014\022\013\n\003ret\030\002 \001(\010\022\030\n\013rs_sig_data\030\003 "
  "\001(\014H\000\210\001\001B\016\n\014_rs_sig_data\"D\n\006Grappa\022\022\n\ngr"
  "appaData\030\001 \001(\014\022\031\n\021grappa_session_id\030\002 \001("
  "\r\022\013\n\003ret\030\003 \001(\010\"\034\n\014rqGeneGrappa\022\014\n\004udid\030\001"
  " \001(\t\"f\n\006scinfo\022\017\n\007appleid\030\001 \001(\t\022\014\n\004dsid\030"
  "\002 \001(\003\022\014\n\004sidb\030\003 \001(\014\022\014\n\004sidd\030\004 \001(\014\022\013\n\003txt"
  "\030\005 \001(\014\022\024\n\014hardwareInfo\030\006 \001(\014\"\027\n\010rsscinfo"
  "\022\013\n\003ret\030\001 \001(\0102\343\001\n\003aid\022J\n\nGenerateRS\022!.Ap"
  "pleRemoteAuth.RemoteDeviceInfo\032\027.AppleRe"
  "moteAuth.rsdata\"\000\022J\n\016GenerateGrappa\022\035.Ap"
  "pleRemoteAuth.rqGeneGrappa\032\027.AppleRemote"
  "Auth.Grappa\"\000\022D\n\014UploadScinfo\022\027.AppleRem"
  "oteAuth.scinfo\032\031.AppleRemoteAuth.rsscinf"
  "o\"\000b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_GenerateRS_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_GenerateRS_2eproto = {
    false, false, 811, descriptor_table_protodef_GenerateRS_2eproto,
    "GenerateRS.proto",
    &descriptor_table_GenerateRS_2eproto_once, nullptr, 0, 6,
    schemas, file_default_instances, TableStruct_GenerateRS_2eproto::offsets,
    file_level_metadata_GenerateRS_2eproto, file_level_enum_descriptors_GenerateRS_2eproto,
    file_level_service_descriptors_GenerateRS_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_GenerateRS_2eproto_getter() {
  return &descriptor_table_GenerateRS_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_GenerateRS_2eproto(&descriptor_table_GenerateRS_2eproto);
namespace AppleRemoteAuth {

// ===================================================================

class RemoteDeviceInfo::_Internal {
 public:
  using HasBits = decltype(std::declval<RemoteDeviceInfo>()._impl_._has_bits_);
  static void set_has_grappa(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_dsid(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

RemoteDeviceInfo::RemoteDeviceInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:AppleRemoteAuth.RemoteDeviceInfo)
}
RemoteDeviceInfo::RemoteDeviceInfo(const RemoteDeviceInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  RemoteDeviceInfo* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.rq_data_){}
    , decltype(_impl_.rq_sig_data_){}
    , decltype(_impl_.fair_play_certificate_){}
    , decltype(_impl_.fair_play_guid_){}
    , decltype(_impl_.grappa_){}
    , decltype(_impl_.fair_device_type_){}
    , decltype(_impl_.dsid_){}
    , decltype(_impl_.grappa_session_id_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.rq_data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.rq_data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_rq_data().empty()) {
    _this->_impl_.rq_data_.Set(from._internal_rq_data(), 
      _this->GetArenaForAllocation());
  }
  _impl_.rq_sig_data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.rq_sig_data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_rq_sig_data().empty()) {
    _this->_impl_.rq_sig_data_.Set(from._internal_rq_sig_data(), 
      _this->GetArenaForAllocation());
  }
  _impl_.fair_play_certificate_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.fair_play_certificate_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_fair_play_certificate().empty()) {
    _this->_impl_.fair_play_certificate_.Set(from._internal_fair_play_certificate(), 
      _this->GetArenaForAllocation());
  }
  _impl_.fair_play_guid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.fair_play_guid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_fair_play_guid().empty()) {
    _this->_impl_.fair_play_guid_.Set(from._internal_fair_play_guid(), 
      _this->GetArenaForAllocation());
  }
  _impl_.grappa_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.grappa_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_grappa()) {
    _this->_impl_.grappa_.Set(from._internal_grappa(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.fair_device_type_, &from._impl_.fair_device_type_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.grappa_session_id_) -
    reinterpret_cast<char*>(&_impl_.fair_device_type_)) + sizeof(_impl_.grappa_session_id_));
  // @@protoc_insertion_point(copy_constructor:AppleRemoteAuth.RemoteDeviceInfo)
}

inline void RemoteDeviceInfo::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.rq_data_){}
    , decltype(_impl_.rq_sig_data_){}
    , decltype(_impl_.fair_play_certificate_){}
    , decltype(_impl_.fair_play_guid_){}
    , decltype(_impl_.grappa_){}
    , decltype(_impl_.fair_device_type_){int64_t{0}}
    , decltype(_impl_.dsid_){int64_t{0}}
    , decltype(_impl_.grappa_session_id_){0u}
  };
  _impl_.rq_data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.rq_data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.rq_sig_data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.rq_sig_data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.fair_play_certificate_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.fair_play_certificate_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.fair_play_guid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.fair_play_guid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.grappa_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.grappa_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

RemoteDeviceInfo::~RemoteDeviceInfo() {
  // @@protoc_insertion_point(destructor:AppleRemoteAuth.RemoteDeviceInfo)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void RemoteDeviceInfo::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.rq_data_.Destroy();
  _impl_.rq_sig_data_.Destroy();
  _impl_.fair_play_certificate_.Destroy();
  _impl_.fair_play_guid_.Destroy();
  _impl_.grappa_.Destroy();
}

void RemoteDeviceInfo::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void RemoteDeviceInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:AppleRemoteAuth.RemoteDeviceInfo)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.rq_data_.ClearToEmpty();
  _impl_.rq_sig_data_.ClearToEmpty();
  _impl_.fair_play_certificate_.ClearToEmpty();
  _impl_.fair_play_guid_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.grappa_.ClearNonDefaultToEmpty();
  }
  _impl_.fair_device_type_ = int64_t{0};
  _impl_.dsid_ = int64_t{0};
  _impl_.grappa_session_id_ = 0u;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RemoteDeviceInfo::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bytes rq_data = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_rq_data();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes rq_sig_data = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_rq_sig_data();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 grappa_session_id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.grappa_session_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes fair_play_certificate = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          auto str = _internal_mutable_fair_play_certificate();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 fair_device_type = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.fair_device_type_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string fair_play_guid = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 66)) {
          auto str = _internal_mutable_fair_play_guid();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "AppleRemoteAuth.RemoteDeviceInfo.fair_play_guid"));
        } else
          goto handle_unusual;
        continue;
      // optional bytes grappa = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 74)) {
          auto str = _internal_mutable_grappa();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional int64 dsid = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 80)) {
          _Internal::set_has_dsid(&has_bits);
          _impl_.dsid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* RemoteDeviceInfo::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:AppleRemoteAuth.RemoteDeviceInfo)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes rq_data = 1;
  if (!this->_internal_rq_data().empty()) {
    target = stream->WriteBytesMaybeAliased(
        1, this->_internal_rq_data(), target);
  }

  // bytes rq_sig_data = 2;
  if (!this->_internal_rq_sig_data().empty()) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_rq_sig_data(), target);
  }

  // uint32 grappa_session_id = 3;
  if (this->_internal_grappa_session_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(3, this->_internal_grappa_session_id(), target);
  }

  // bytes fair_play_certificate = 5;
  if (!this->_internal_fair_play_certificate().empty()) {
    target = stream->WriteBytesMaybeAliased(
        5, this->_internal_fair_play_certificate(), target);
  }

  // int64 fair_device_type = 6;
  if (this->_internal_fair_device_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(6, this->_internal_fair_device_type(), target);
  }

  // string fair_play_guid = 8;
  if (!this->_internal_fair_play_guid().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_fair_play_guid().data(), static_cast<int>(this->_internal_fair_play_guid().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "AppleRemoteAuth.RemoteDeviceInfo.fair_play_guid");
    target = stream->WriteStringMaybeAliased(
        8, this->_internal_fair_play_guid(), target);
  }

  // optional bytes grappa = 9;
  if (_internal_has_grappa()) {
    target = stream->WriteBytesMaybeAliased(
        9, this->_internal_grappa(), target);
  }

  // optional int64 dsid = 10;
  if (_internal_has_dsid()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(10, this->_internal_dsid(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:AppleRemoteAuth.RemoteDeviceInfo)
  return target;
}

size_t RemoteDeviceInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:AppleRemoteAuth.RemoteDeviceInfo)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes rq_data = 1;
  if (!this->_internal_rq_data().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_rq_data());
  }

  // bytes rq_sig_data = 2;
  if (!this->_internal_rq_sig_data().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_rq_sig_data());
  }

  // bytes fair_play_certificate = 5;
  if (!this->_internal_fair_play_certificate().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_fair_play_certificate());
  }

  // string fair_play_guid = 8;
  if (!this->_internal_fair_play_guid().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_fair_play_guid());
  }

  // optional bytes grappa = 9;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_grappa());
  }

  // int64 fair_device_type = 6;
  if (this->_internal_fair_device_type() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_fair_device_type());
  }

  // optional int64 dsid = 10;
  if (cached_has_bits & 0x00000002u) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_dsid());
  }

  // uint32 grappa_session_id = 3;
  if (this->_internal_grappa_session_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_grappa_session_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData RemoteDeviceInfo::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    RemoteDeviceInfo::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*RemoteDeviceInfo::GetClassData() const { return &_class_data_; }


void RemoteDeviceInfo::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<RemoteDeviceInfo*>(&to_msg);
  auto& from = static_cast<const RemoteDeviceInfo&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:AppleRemoteAuth.RemoteDeviceInfo)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_rq_data().empty()) {
    _this->_internal_set_rq_data(from._internal_rq_data());
  }
  if (!from._internal_rq_sig_data().empty()) {
    _this->_internal_set_rq_sig_data(from._internal_rq_sig_data());
  }
  if (!from._internal_fair_play_certificate().empty()) {
    _this->_internal_set_fair_play_certificate(from._internal_fair_play_certificate());
  }
  if (!from._internal_fair_play_guid().empty()) {
    _this->_internal_set_fair_play_guid(from._internal_fair_play_guid());
  }
  if (from._internal_has_grappa()) {
    _this->_internal_set_grappa(from._internal_grappa());
  }
  if (from._internal_fair_device_type() != 0) {
    _this->_internal_set_fair_device_type(from._internal_fair_device_type());
  }
  if (from._internal_has_dsid()) {
    _this->_internal_set_dsid(from._internal_dsid());
  }
  if (from._internal_grappa_session_id() != 0) {
    _this->_internal_set_grappa_session_id(from._internal_grappa_session_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void RemoteDeviceInfo::CopyFrom(const RemoteDeviceInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:AppleRemoteAuth.RemoteDeviceInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RemoteDeviceInfo::IsInitialized() const {
  return true;
}

void RemoteDeviceInfo::InternalSwap(RemoteDeviceInfo* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.rq_data_, lhs_arena,
      &other->_impl_.rq_data_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.rq_sig_data_, lhs_arena,
      &other->_impl_.rq_sig_data_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.fair_play_certificate_, lhs_arena,
      &other->_impl_.fair_play_certificate_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.fair_play_guid_, lhs_arena,
      &other->_impl_.fair_play_guid_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.grappa_, lhs_arena,
      &other->_impl_.grappa_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RemoteDeviceInfo, _impl_.grappa_session_id_)
      + sizeof(RemoteDeviceInfo::_impl_.grappa_session_id_)
      - PROTOBUF_FIELD_OFFSET(RemoteDeviceInfo, _impl_.fair_device_type_)>(
          reinterpret_cast<char*>(&_impl_.fair_device_type_),
          reinterpret_cast<char*>(&other->_impl_.fair_device_type_));
}

::PROTOBUF_NAMESPACE_ID::Metadata RemoteDeviceInfo::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_GenerateRS_2eproto_getter, &descriptor_table_GenerateRS_2eproto_once,
      file_level_metadata_GenerateRS_2eproto[0]);
}

// ===================================================================

class rsdata::_Internal {
 public:
  using HasBits = decltype(std::declval<rsdata>()._impl_._has_bits_);
  static void set_has_rs_sig_data(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

rsdata::rsdata(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:AppleRemoteAuth.rsdata)
}
rsdata::rsdata(const rsdata& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  rsdata* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.rs_data_){}
    , decltype(_impl_.rs_sig_data_){}
    , decltype(_impl_.ret_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.rs_data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.rs_data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_rs_data().empty()) {
    _this->_impl_.rs_data_.Set(from._internal_rs_data(), 
      _this->GetArenaForAllocation());
  }
  _impl_.rs_sig_data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.rs_sig_data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_rs_sig_data()) {
    _this->_impl_.rs_sig_data_.Set(from._internal_rs_sig_data(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.ret_ = from._impl_.ret_;
  // @@protoc_insertion_point(copy_constructor:AppleRemoteAuth.rsdata)
}

inline void rsdata::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.rs_data_){}
    , decltype(_impl_.rs_sig_data_){}
    , decltype(_impl_.ret_){false}
  };
  _impl_.rs_data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.rs_data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.rs_sig_data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.rs_sig_data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

rsdata::~rsdata() {
  // @@protoc_insertion_point(destructor:AppleRemoteAuth.rsdata)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void rsdata::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.rs_data_.Destroy();
  _impl_.rs_sig_data_.Destroy();
}

void rsdata::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void rsdata::Clear() {
// @@protoc_insertion_point(message_clear_start:AppleRemoteAuth.rsdata)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.rs_data_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.rs_sig_data_.ClearNonDefaultToEmpty();
  }
  _impl_.ret_ = false;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* rsdata::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bytes rs_data = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_rs_data();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool ret = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.ret_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional bytes rs_sig_data = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_rs_sig_data();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* rsdata::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:AppleRemoteAuth.rsdata)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes rs_data = 1;
  if (!this->_internal_rs_data().empty()) {
    target = stream->WriteBytesMaybeAliased(
        1, this->_internal_rs_data(), target);
  }

  // bool ret = 2;
  if (this->_internal_ret() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(2, this->_internal_ret(), target);
  }

  // optional bytes rs_sig_data = 3;
  if (_internal_has_rs_sig_data()) {
    target = stream->WriteBytesMaybeAliased(
        3, this->_internal_rs_sig_data(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:AppleRemoteAuth.rsdata)
  return target;
}

size_t rsdata::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:AppleRemoteAuth.rsdata)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes rs_data = 1;
  if (!this->_internal_rs_data().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_rs_data());
  }

  // optional bytes rs_sig_data = 3;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_rs_sig_data());
  }

  // bool ret = 2;
  if (this->_internal_ret() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData rsdata::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    rsdata::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*rsdata::GetClassData() const { return &_class_data_; }


void rsdata::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<rsdata*>(&to_msg);
  auto& from = static_cast<const rsdata&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:AppleRemoteAuth.rsdata)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_rs_data().empty()) {
    _this->_internal_set_rs_data(from._internal_rs_data());
  }
  if (from._internal_has_rs_sig_data()) {
    _this->_internal_set_rs_sig_data(from._internal_rs_sig_data());
  }
  if (from._internal_ret() != 0) {
    _this->_internal_set_ret(from._internal_ret());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void rsdata::CopyFrom(const rsdata& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:AppleRemoteAuth.rsdata)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool rsdata::IsInitialized() const {
  return true;
}

void rsdata::InternalSwap(rsdata* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.rs_data_, lhs_arena,
      &other->_impl_.rs_data_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.rs_sig_data_, lhs_arena,
      &other->_impl_.rs_sig_data_, rhs_arena
  );
  swap(_impl_.ret_, other->_impl_.ret_);
}

::PROTOBUF_NAMESPACE_ID::Metadata rsdata::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_GenerateRS_2eproto_getter, &descriptor_table_GenerateRS_2eproto_once,
      file_level_metadata_GenerateRS_2eproto[1]);
}

// ===================================================================

class Grappa::_Internal {
 public:
};

Grappa::Grappa(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:AppleRemoteAuth.Grappa)
}
Grappa::Grappa(const Grappa& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Grappa* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.grappadata_){}
    , decltype(_impl_.grappa_session_id_){}
    , decltype(_impl_.ret_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.grappadata_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.grappadata_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_grappadata().empty()) {
    _this->_impl_.grappadata_.Set(from._internal_grappadata(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.grappa_session_id_, &from._impl_.grappa_session_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.ret_) -
    reinterpret_cast<char*>(&_impl_.grappa_session_id_)) + sizeof(_impl_.ret_));
  // @@protoc_insertion_point(copy_constructor:AppleRemoteAuth.Grappa)
}

inline void Grappa::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.grappadata_){}
    , decltype(_impl_.grappa_session_id_){0u}
    , decltype(_impl_.ret_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.grappadata_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.grappadata_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

Grappa::~Grappa() {
  // @@protoc_insertion_point(destructor:AppleRemoteAuth.Grappa)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Grappa::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.grappadata_.Destroy();
}

void Grappa::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Grappa::Clear() {
// @@protoc_insertion_point(message_clear_start:AppleRemoteAuth.Grappa)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.grappadata_.ClearToEmpty();
  ::memset(&_impl_.grappa_session_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.ret_) -
      reinterpret_cast<char*>(&_impl_.grappa_session_id_)) + sizeof(_impl_.ret_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Grappa::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bytes grappaData = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_grappadata();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 grappa_session_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.grappa_session_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool ret = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.ret_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Grappa::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:AppleRemoteAuth.Grappa)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes grappaData = 1;
  if (!this->_internal_grappadata().empty()) {
    target = stream->WriteBytesMaybeAliased(
        1, this->_internal_grappadata(), target);
  }

  // uint32 grappa_session_id = 2;
  if (this->_internal_grappa_session_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_grappa_session_id(), target);
  }

  // bool ret = 3;
  if (this->_internal_ret() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(3, this->_internal_ret(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:AppleRemoteAuth.Grappa)
  return target;
}

size_t Grappa::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:AppleRemoteAuth.Grappa)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes grappaData = 1;
  if (!this->_internal_grappadata().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_grappadata());
  }

  // uint32 grappa_session_id = 2;
  if (this->_internal_grappa_session_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_grappa_session_id());
  }

  // bool ret = 3;
  if (this->_internal_ret() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Grappa::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Grappa::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Grappa::GetClassData() const { return &_class_data_; }


void Grappa::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Grappa*>(&to_msg);
  auto& from = static_cast<const Grappa&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:AppleRemoteAuth.Grappa)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_grappadata().empty()) {
    _this->_internal_set_grappadata(from._internal_grappadata());
  }
  if (from._internal_grappa_session_id() != 0) {
    _this->_internal_set_grappa_session_id(from._internal_grappa_session_id());
  }
  if (from._internal_ret() != 0) {
    _this->_internal_set_ret(from._internal_ret());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Grappa::CopyFrom(const Grappa& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:AppleRemoteAuth.Grappa)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Grappa::IsInitialized() const {
  return true;
}

void Grappa::InternalSwap(Grappa* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.grappadata_, lhs_arena,
      &other->_impl_.grappadata_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Grappa, _impl_.ret_)
      + sizeof(Grappa::_impl_.ret_)
      - PROTOBUF_FIELD_OFFSET(Grappa, _impl_.grappa_session_id_)>(
          reinterpret_cast<char*>(&_impl_.grappa_session_id_),
          reinterpret_cast<char*>(&other->_impl_.grappa_session_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Grappa::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_GenerateRS_2eproto_getter, &descriptor_table_GenerateRS_2eproto_once,
      file_level_metadata_GenerateRS_2eproto[2]);
}

// ===================================================================

class rqGeneGrappa::_Internal {
 public:
};

rqGeneGrappa::rqGeneGrappa(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:AppleRemoteAuth.rqGeneGrappa)
}
rqGeneGrappa::rqGeneGrappa(const rqGeneGrappa& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  rqGeneGrappa* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.udid_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.udid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.udid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_udid().empty()) {
    _this->_impl_.udid_.Set(from._internal_udid(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:AppleRemoteAuth.rqGeneGrappa)
}

inline void rqGeneGrappa::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.udid_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.udid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.udid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

rqGeneGrappa::~rqGeneGrappa() {
  // @@protoc_insertion_point(destructor:AppleRemoteAuth.rqGeneGrappa)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void rqGeneGrappa::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.udid_.Destroy();
}

void rqGeneGrappa::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void rqGeneGrappa::Clear() {
// @@protoc_insertion_point(message_clear_start:AppleRemoteAuth.rqGeneGrappa)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.udid_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* rqGeneGrappa::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string udid = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_udid();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "AppleRemoteAuth.rqGeneGrappa.udid"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* rqGeneGrappa::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:AppleRemoteAuth.rqGeneGrappa)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string udid = 1;
  if (!this->_internal_udid().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_udid().data(), static_cast<int>(this->_internal_udid().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "AppleRemoteAuth.rqGeneGrappa.udid");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_udid(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:AppleRemoteAuth.rqGeneGrappa)
  return target;
}

size_t rqGeneGrappa::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:AppleRemoteAuth.rqGeneGrappa)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string udid = 1;
  if (!this->_internal_udid().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_udid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData rqGeneGrappa::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    rqGeneGrappa::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*rqGeneGrappa::GetClassData() const { return &_class_data_; }


void rqGeneGrappa::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<rqGeneGrappa*>(&to_msg);
  auto& from = static_cast<const rqGeneGrappa&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:AppleRemoteAuth.rqGeneGrappa)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_udid().empty()) {
    _this->_internal_set_udid(from._internal_udid());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void rqGeneGrappa::CopyFrom(const rqGeneGrappa& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:AppleRemoteAuth.rqGeneGrappa)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool rqGeneGrappa::IsInitialized() const {
  return true;
}

void rqGeneGrappa::InternalSwap(rqGeneGrappa* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.udid_, lhs_arena,
      &other->_impl_.udid_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata rqGeneGrappa::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_GenerateRS_2eproto_getter, &descriptor_table_GenerateRS_2eproto_once,
      file_level_metadata_GenerateRS_2eproto[3]);
}

// ===================================================================

class scinfo::_Internal {
 public:
};

scinfo::scinfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:AppleRemoteAuth.scinfo)
}
scinfo::scinfo(const scinfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  scinfo* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.appleid_){}
    , decltype(_impl_.sidb_){}
    , decltype(_impl_.sidd_){}
    , decltype(_impl_.txt_){}
    , decltype(_impl_.hardwareinfo_){}
    , decltype(_impl_.dsid_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.appleid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.appleid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_appleid().empty()) {
    _this->_impl_.appleid_.Set(from._internal_appleid(), 
      _this->GetArenaForAllocation());
  }
  _impl_.sidb_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.sidb_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_sidb().empty()) {
    _this->_impl_.sidb_.Set(from._internal_sidb(), 
      _this->GetArenaForAllocation());
  }
  _impl_.sidd_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.sidd_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_sidd().empty()) {
    _this->_impl_.sidd_.Set(from._internal_sidd(), 
      _this->GetArenaForAllocation());
  }
  _impl_.txt_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.txt_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_txt().empty()) {
    _this->_impl_.txt_.Set(from._internal_txt(), 
      _this->GetArenaForAllocation());
  }
  _impl_.hardwareinfo_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.hardwareinfo_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_hardwareinfo().empty()) {
    _this->_impl_.hardwareinfo_.Set(from._internal_hardwareinfo(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.dsid_ = from._impl_.dsid_;
  // @@protoc_insertion_point(copy_constructor:AppleRemoteAuth.scinfo)
}

inline void scinfo::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.appleid_){}
    , decltype(_impl_.sidb_){}
    , decltype(_impl_.sidd_){}
    , decltype(_impl_.txt_){}
    , decltype(_impl_.hardwareinfo_){}
    , decltype(_impl_.dsid_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.appleid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.appleid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.sidb_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.sidb_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.sidd_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.sidd_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.txt_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.txt_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.hardwareinfo_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.hardwareinfo_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

scinfo::~scinfo() {
  // @@protoc_insertion_point(destructor:AppleRemoteAuth.scinfo)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void scinfo::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.appleid_.Destroy();
  _impl_.sidb_.Destroy();
  _impl_.sidd_.Destroy();
  _impl_.txt_.Destroy();
  _impl_.hardwareinfo_.Destroy();
}

void scinfo::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void scinfo::Clear() {
// @@protoc_insertion_point(message_clear_start:AppleRemoteAuth.scinfo)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.appleid_.ClearToEmpty();
  _impl_.sidb_.ClearToEmpty();
  _impl_.sidd_.ClearToEmpty();
  _impl_.txt_.ClearToEmpty();
  _impl_.hardwareinfo_.ClearToEmpty();
  _impl_.dsid_ = int64_t{0};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* scinfo::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string appleid = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_appleid();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "AppleRemoteAuth.scinfo.appleid"));
        } else
          goto handle_unusual;
        continue;
      // int64 dsid = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.dsid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes sidb = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_sidb();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes sidd = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_sidd();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes txt = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          auto str = _internal_mutable_txt();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes hardwareInfo = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          auto str = _internal_mutable_hardwareinfo();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* scinfo::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:AppleRemoteAuth.scinfo)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string appleid = 1;
  if (!this->_internal_appleid().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_appleid().data(), static_cast<int>(this->_internal_appleid().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "AppleRemoteAuth.scinfo.appleid");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_appleid(), target);
  }

  // int64 dsid = 2;
  if (this->_internal_dsid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(2, this->_internal_dsid(), target);
  }

  // bytes sidb = 3;
  if (!this->_internal_sidb().empty()) {
    target = stream->WriteBytesMaybeAliased(
        3, this->_internal_sidb(), target);
  }

  // bytes sidd = 4;
  if (!this->_internal_sidd().empty()) {
    target = stream->WriteBytesMaybeAliased(
        4, this->_internal_sidd(), target);
  }

  // bytes txt = 5;
  if (!this->_internal_txt().empty()) {
    target = stream->WriteBytesMaybeAliased(
        5, this->_internal_txt(), target);
  }

  // bytes hardwareInfo = 6;
  if (!this->_internal_hardwareinfo().empty()) {
    target = stream->WriteBytesMaybeAliased(
        6, this->_internal_hardwareinfo(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:AppleRemoteAuth.scinfo)
  return target;
}

size_t scinfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:AppleRemoteAuth.scinfo)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string appleid = 1;
  if (!this->_internal_appleid().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_appleid());
  }

  // bytes sidb = 3;
  if (!this->_internal_sidb().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_sidb());
  }

  // bytes sidd = 4;
  if (!this->_internal_sidd().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_sidd());
  }

  // bytes txt = 5;
  if (!this->_internal_txt().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_txt());
  }

  // bytes hardwareInfo = 6;
  if (!this->_internal_hardwareinfo().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_hardwareinfo());
  }

  // int64 dsid = 2;
  if (this->_internal_dsid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_dsid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData scinfo::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    scinfo::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*scinfo::GetClassData() const { return &_class_data_; }


void scinfo::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<scinfo*>(&to_msg);
  auto& from = static_cast<const scinfo&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:AppleRemoteAuth.scinfo)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_appleid().empty()) {
    _this->_internal_set_appleid(from._internal_appleid());
  }
  if (!from._internal_sidb().empty()) {
    _this->_internal_set_sidb(from._internal_sidb());
  }
  if (!from._internal_sidd().empty()) {
    _this->_internal_set_sidd(from._internal_sidd());
  }
  if (!from._internal_txt().empty()) {
    _this->_internal_set_txt(from._internal_txt());
  }
  if (!from._internal_hardwareinfo().empty()) {
    _this->_internal_set_hardwareinfo(from._internal_hardwareinfo());
  }
  if (from._internal_dsid() != 0) {
    _this->_internal_set_dsid(from._internal_dsid());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void scinfo::CopyFrom(const scinfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:AppleRemoteAuth.scinfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool scinfo::IsInitialized() const {
  return true;
}

void scinfo::InternalSwap(scinfo* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.appleid_, lhs_arena,
      &other->_impl_.appleid_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.sidb_, lhs_arena,
      &other->_impl_.sidb_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.sidd_, lhs_arena,
      &other->_impl_.sidd_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.txt_, lhs_arena,
      &other->_impl_.txt_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.hardwareinfo_, lhs_arena,
      &other->_impl_.hardwareinfo_, rhs_arena
  );
  swap(_impl_.dsid_, other->_impl_.dsid_);
}

::PROTOBUF_NAMESPACE_ID::Metadata scinfo::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_GenerateRS_2eproto_getter, &descriptor_table_GenerateRS_2eproto_once,
      file_level_metadata_GenerateRS_2eproto[4]);
}

// ===================================================================

class rsscinfo::_Internal {
 public:
};

rsscinfo::rsscinfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:AppleRemoteAuth.rsscinfo)
}
rsscinfo::rsscinfo(const rsscinfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  rsscinfo* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.ret_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.ret_ = from._impl_.ret_;
  // @@protoc_insertion_point(copy_constructor:AppleRemoteAuth.rsscinfo)
}

inline void rsscinfo::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.ret_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

rsscinfo::~rsscinfo() {
  // @@protoc_insertion_point(destructor:AppleRemoteAuth.rsscinfo)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void rsscinfo::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void rsscinfo::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void rsscinfo::Clear() {
// @@protoc_insertion_point(message_clear_start:AppleRemoteAuth.rsscinfo)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.ret_ = false;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* rsscinfo::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bool ret = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.ret_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* rsscinfo::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:AppleRemoteAuth.rsscinfo)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bool ret = 1;
  if (this->_internal_ret() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(1, this->_internal_ret(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:AppleRemoteAuth.rsscinfo)
  return target;
}

size_t rsscinfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:AppleRemoteAuth.rsscinfo)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bool ret = 1;
  if (this->_internal_ret() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData rsscinfo::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    rsscinfo::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*rsscinfo::GetClassData() const { return &_class_data_; }


void rsscinfo::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<rsscinfo*>(&to_msg);
  auto& from = static_cast<const rsscinfo&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:AppleRemoteAuth.rsscinfo)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_ret() != 0) {
    _this->_internal_set_ret(from._internal_ret());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void rsscinfo::CopyFrom(const rsscinfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:AppleRemoteAuth.rsscinfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool rsscinfo::IsInitialized() const {
  return true;
}

void rsscinfo::InternalSwap(rsscinfo* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.ret_, other->_impl_.ret_);
}

::PROTOBUF_NAMESPACE_ID::Metadata rsscinfo::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_GenerateRS_2eproto_getter, &descriptor_table_GenerateRS_2eproto_once,
      file_level_metadata_GenerateRS_2eproto[5]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace AppleRemoteAuth
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::AppleRemoteAuth::RemoteDeviceInfo*
Arena::CreateMaybeMessage< ::AppleRemoteAuth::RemoteDeviceInfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::AppleRemoteAuth::RemoteDeviceInfo >(arena);
}
template<> PROTOBUF_NOINLINE ::AppleRemoteAuth::rsdata*
Arena::CreateMaybeMessage< ::AppleRemoteAuth::rsdata >(Arena* arena) {
  return Arena::CreateMessageInternal< ::AppleRemoteAuth::rsdata >(arena);
}
template<> PROTOBUF_NOINLINE ::AppleRemoteAuth::Grappa*
Arena::CreateMaybeMessage< ::AppleRemoteAuth::Grappa >(Arena* arena) {
  return Arena::CreateMessageInternal< ::AppleRemoteAuth::Grappa >(arena);
}
template<> PROTOBUF_NOINLINE ::AppleRemoteAuth::rqGeneGrappa*
Arena::CreateMaybeMessage< ::AppleRemoteAuth::rqGeneGrappa >(Arena* arena) {
  return Arena::CreateMessageInternal< ::AppleRemoteAuth::rqGeneGrappa >(arena);
}
template<> PROTOBUF_NOINLINE ::AppleRemoteAuth::scinfo*
Arena::CreateMaybeMessage< ::AppleRemoteAuth::scinfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::AppleRemoteAuth::scinfo >(arena);
}
template<> PROTOBUF_NOINLINE ::AppleRemoteAuth::rsscinfo*
Arena::CreateMaybeMessage< ::AppleRemoteAuth::rsscinfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::AppleRemoteAuth::rsscinfo >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
