// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: GenerateRS.proto
// Original file comments:
// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef GRPC_GenerateRS_2eproto__INCLUDED
#define GRPC_GenerateRS_2eproto__INCLUDED

#include "GenerateRS.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace AppleRemoteAuth {

// The aid service definition.
class aid final {
 public:
  static constexpr char const* service_full_name() {
    return "AppleRemoteAuth.aid";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // 生成rs和rs.sig 文件信息
    virtual ::grpc::Status GenerateRS(::grpc::ClientContext* context, const ::AppleRemoteAuth::RemoteDeviceInfo& request, ::AppleRemoteAuth::rsdata* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::AppleRemoteAuth::rsdata>> AsyncGenerateRS(::grpc::ClientContext* context, const ::AppleRemoteAuth::RemoteDeviceInfo& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::AppleRemoteAuth::rsdata>>(AsyncGenerateRSRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::AppleRemoteAuth::rsdata>> PrepareAsyncGenerateRS(::grpc::ClientContext* context, const ::AppleRemoteAuth::RemoteDeviceInfo& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::AppleRemoteAuth::rsdata>>(PrepareAsyncGenerateRSRaw(context, request, cq));
    }
    // 生成 Grappa 信息
    virtual ::grpc::Status GenerateGrappa(::grpc::ClientContext* context, const ::AppleRemoteAuth::rqGeneGrappa& request, ::AppleRemoteAuth::Grappa* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::AppleRemoteAuth::Grappa>> AsyncGenerateGrappa(::grpc::ClientContext* context, const ::AppleRemoteAuth::rqGeneGrappa& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::AppleRemoteAuth::Grappa>>(AsyncGenerateGrappaRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::AppleRemoteAuth::Grappa>> PrepareAsyncGenerateGrappa(::grpc::ClientContext* context, const ::AppleRemoteAuth::rqGeneGrappa& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::AppleRemoteAuth::Grappa>>(PrepareAsyncGenerateGrappaRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // 生成rs和rs.sig 文件信息
      virtual void GenerateRS(::grpc::ClientContext* context, const ::AppleRemoteAuth::RemoteDeviceInfo* request, ::AppleRemoteAuth::rsdata* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GenerateRS(::grpc::ClientContext* context, const ::AppleRemoteAuth::RemoteDeviceInfo* request, ::AppleRemoteAuth::rsdata* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 生成 Grappa 信息
      virtual void GenerateGrappa(::grpc::ClientContext* context, const ::AppleRemoteAuth::rqGeneGrappa* request, ::AppleRemoteAuth::Grappa* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GenerateGrappa(::grpc::ClientContext* context, const ::AppleRemoteAuth::rqGeneGrappa* request, ::AppleRemoteAuth::Grappa* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::AppleRemoteAuth::rsdata>* AsyncGenerateRSRaw(::grpc::ClientContext* context, const ::AppleRemoteAuth::RemoteDeviceInfo& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::AppleRemoteAuth::rsdata>* PrepareAsyncGenerateRSRaw(::grpc::ClientContext* context, const ::AppleRemoteAuth::RemoteDeviceInfo& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::AppleRemoteAuth::Grappa>* AsyncGenerateGrappaRaw(::grpc::ClientContext* context, const ::AppleRemoteAuth::rqGeneGrappa& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::AppleRemoteAuth::Grappa>* PrepareAsyncGenerateGrappaRaw(::grpc::ClientContext* context, const ::AppleRemoteAuth::rqGeneGrappa& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GenerateRS(::grpc::ClientContext* context, const ::AppleRemoteAuth::RemoteDeviceInfo& request, ::AppleRemoteAuth::rsdata* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::AppleRemoteAuth::rsdata>> AsyncGenerateRS(::grpc::ClientContext* context, const ::AppleRemoteAuth::RemoteDeviceInfo& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::AppleRemoteAuth::rsdata>>(AsyncGenerateRSRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::AppleRemoteAuth::rsdata>> PrepareAsyncGenerateRS(::grpc::ClientContext* context, const ::AppleRemoteAuth::RemoteDeviceInfo& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::AppleRemoteAuth::rsdata>>(PrepareAsyncGenerateRSRaw(context, request, cq));
    }
    ::grpc::Status GenerateGrappa(::grpc::ClientContext* context, const ::AppleRemoteAuth::rqGeneGrappa& request, ::AppleRemoteAuth::Grappa* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::AppleRemoteAuth::Grappa>> AsyncGenerateGrappa(::grpc::ClientContext* context, const ::AppleRemoteAuth::rqGeneGrappa& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::AppleRemoteAuth::Grappa>>(AsyncGenerateGrappaRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::AppleRemoteAuth::Grappa>> PrepareAsyncGenerateGrappa(::grpc::ClientContext* context, const ::AppleRemoteAuth::rqGeneGrappa& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::AppleRemoteAuth::Grappa>>(PrepareAsyncGenerateGrappaRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GenerateRS(::grpc::ClientContext* context, const ::AppleRemoteAuth::RemoteDeviceInfo* request, ::AppleRemoteAuth::rsdata* response, std::function<void(::grpc::Status)>) override;
      void GenerateRS(::grpc::ClientContext* context, const ::AppleRemoteAuth::RemoteDeviceInfo* request, ::AppleRemoteAuth::rsdata* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GenerateGrappa(::grpc::ClientContext* context, const ::AppleRemoteAuth::rqGeneGrappa* request, ::AppleRemoteAuth::Grappa* response, std::function<void(::grpc::Status)>) override;
      void GenerateGrappa(::grpc::ClientContext* context, const ::AppleRemoteAuth::rqGeneGrappa* request, ::AppleRemoteAuth::Grappa* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::AppleRemoteAuth::rsdata>* AsyncGenerateRSRaw(::grpc::ClientContext* context, const ::AppleRemoteAuth::RemoteDeviceInfo& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::AppleRemoteAuth::rsdata>* PrepareAsyncGenerateRSRaw(::grpc::ClientContext* context, const ::AppleRemoteAuth::RemoteDeviceInfo& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::AppleRemoteAuth::Grappa>* AsyncGenerateGrappaRaw(::grpc::ClientContext* context, const ::AppleRemoteAuth::rqGeneGrappa& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::AppleRemoteAuth::Grappa>* PrepareAsyncGenerateGrappaRaw(::grpc::ClientContext* context, const ::AppleRemoteAuth::rqGeneGrappa& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GenerateRS_;
    const ::grpc::internal::RpcMethod rpcmethod_GenerateGrappa_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // 生成rs和rs.sig 文件信息
    virtual ::grpc::Status GenerateRS(::grpc::ServerContext* context, const ::AppleRemoteAuth::RemoteDeviceInfo* request, ::AppleRemoteAuth::rsdata* response);
    // 生成 Grappa 信息
    virtual ::grpc::Status GenerateGrappa(::grpc::ServerContext* context, const ::AppleRemoteAuth::rqGeneGrappa* request, ::AppleRemoteAuth::Grappa* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GenerateRS : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GenerateRS() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GenerateRS() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GenerateRS(::grpc::ServerContext* /*context*/, const ::AppleRemoteAuth::RemoteDeviceInfo* /*request*/, ::AppleRemoteAuth::rsdata* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGenerateRS(::grpc::ServerContext* context, ::AppleRemoteAuth::RemoteDeviceInfo* request, ::grpc::ServerAsyncResponseWriter< ::AppleRemoteAuth::rsdata>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GenerateGrappa : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GenerateGrappa() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GenerateGrappa() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GenerateGrappa(::grpc::ServerContext* /*context*/, const ::AppleRemoteAuth::rqGeneGrappa* /*request*/, ::AppleRemoteAuth::Grappa* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGenerateGrappa(::grpc::ServerContext* context, ::AppleRemoteAuth::rqGeneGrappa* request, ::grpc::ServerAsyncResponseWriter< ::AppleRemoteAuth::Grappa>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GenerateRS<WithAsyncMethod_GenerateGrappa<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GenerateRS : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GenerateRS() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::AppleRemoteAuth::RemoteDeviceInfo, ::AppleRemoteAuth::rsdata>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::AppleRemoteAuth::RemoteDeviceInfo* request, ::AppleRemoteAuth::rsdata* response) { return this->GenerateRS(context, request, response); }));}
    void SetMessageAllocatorFor_GenerateRS(
        ::grpc::MessageAllocator< ::AppleRemoteAuth::RemoteDeviceInfo, ::AppleRemoteAuth::rsdata>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::AppleRemoteAuth::RemoteDeviceInfo, ::AppleRemoteAuth::rsdata>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GenerateRS() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GenerateRS(::grpc::ServerContext* /*context*/, const ::AppleRemoteAuth::RemoteDeviceInfo* /*request*/, ::AppleRemoteAuth::rsdata* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GenerateRS(
      ::grpc::CallbackServerContext* /*context*/, const ::AppleRemoteAuth::RemoteDeviceInfo* /*request*/, ::AppleRemoteAuth::rsdata* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GenerateGrappa : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GenerateGrappa() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::AppleRemoteAuth::rqGeneGrappa, ::AppleRemoteAuth::Grappa>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::AppleRemoteAuth::rqGeneGrappa* request, ::AppleRemoteAuth::Grappa* response) { return this->GenerateGrappa(context, request, response); }));}
    void SetMessageAllocatorFor_GenerateGrappa(
        ::grpc::MessageAllocator< ::AppleRemoteAuth::rqGeneGrappa, ::AppleRemoteAuth::Grappa>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::AppleRemoteAuth::rqGeneGrappa, ::AppleRemoteAuth::Grappa>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GenerateGrappa() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GenerateGrappa(::grpc::ServerContext* /*context*/, const ::AppleRemoteAuth::rqGeneGrappa* /*request*/, ::AppleRemoteAuth::Grappa* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GenerateGrappa(
      ::grpc::CallbackServerContext* /*context*/, const ::AppleRemoteAuth::rqGeneGrappa* /*request*/, ::AppleRemoteAuth::Grappa* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GenerateRS<WithCallbackMethod_GenerateGrappa<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GenerateRS : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GenerateRS() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GenerateRS() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GenerateRS(::grpc::ServerContext* /*context*/, const ::AppleRemoteAuth::RemoteDeviceInfo* /*request*/, ::AppleRemoteAuth::rsdata* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GenerateGrappa : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GenerateGrappa() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GenerateGrappa() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GenerateGrappa(::grpc::ServerContext* /*context*/, const ::AppleRemoteAuth::rqGeneGrappa* /*request*/, ::AppleRemoteAuth::Grappa* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GenerateRS : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GenerateRS() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GenerateRS() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GenerateRS(::grpc::ServerContext* /*context*/, const ::AppleRemoteAuth::RemoteDeviceInfo* /*request*/, ::AppleRemoteAuth::rsdata* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGenerateRS(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GenerateGrappa : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GenerateGrappa() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_GenerateGrappa() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GenerateGrappa(::grpc::ServerContext* /*context*/, const ::AppleRemoteAuth::rqGeneGrappa* /*request*/, ::AppleRemoteAuth::Grappa* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGenerateGrappa(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GenerateRS : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GenerateRS() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GenerateRS(context, request, response); }));
    }
    ~WithRawCallbackMethod_GenerateRS() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GenerateRS(::grpc::ServerContext* /*context*/, const ::AppleRemoteAuth::RemoteDeviceInfo* /*request*/, ::AppleRemoteAuth::rsdata* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GenerateRS(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GenerateGrappa : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GenerateGrappa() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GenerateGrappa(context, request, response); }));
    }
    ~WithRawCallbackMethod_GenerateGrappa() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GenerateGrappa(::grpc::ServerContext* /*context*/, const ::AppleRemoteAuth::rqGeneGrappa* /*request*/, ::AppleRemoteAuth::Grappa* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GenerateGrappa(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GenerateRS : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GenerateRS() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::AppleRemoteAuth::RemoteDeviceInfo, ::AppleRemoteAuth::rsdata>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::AppleRemoteAuth::RemoteDeviceInfo, ::AppleRemoteAuth::rsdata>* streamer) {
                       return this->StreamedGenerateRS(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GenerateRS() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GenerateRS(::grpc::ServerContext* /*context*/, const ::AppleRemoteAuth::RemoteDeviceInfo* /*request*/, ::AppleRemoteAuth::rsdata* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGenerateRS(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::AppleRemoteAuth::RemoteDeviceInfo,::AppleRemoteAuth::rsdata>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GenerateGrappa : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GenerateGrappa() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::AppleRemoteAuth::rqGeneGrappa, ::AppleRemoteAuth::Grappa>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::AppleRemoteAuth::rqGeneGrappa, ::AppleRemoteAuth::Grappa>* streamer) {
                       return this->StreamedGenerateGrappa(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GenerateGrappa() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GenerateGrappa(::grpc::ServerContext* /*context*/, const ::AppleRemoteAuth::rqGeneGrappa* /*request*/, ::AppleRemoteAuth::Grappa* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGenerateGrappa(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::AppleRemoteAuth::rqGeneGrappa,::AppleRemoteAuth::Grappa>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GenerateRS<WithStreamedUnaryMethod_GenerateGrappa<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GenerateRS<WithStreamedUnaryMethod_GenerateGrappa<Service > > StreamedService;
};

}  // namespace AppleRemoteAuth


#endif  // GRPC_GenerateRS_2eproto__INCLUDED
